# syntax=docker.io/docker/dockerfile:1

ARG NEXT_PUBLIC_BACKEND_URL

FROM node:18-alpine

WORKDIR /app

# Install bash and curl
RUN apk add --no-cache bash

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./

RUN npm ci --include=optional sharp

# Copy environment variables to the build context
ARG NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}

COPY src ./src
COPY public ./public
COPY next.config.ts .
COPY tsconfig.json .
COPY run.sh ./

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
# ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

# Start Next.js in development mode based on the preferred package manager

RUN chmod +x ./run.sh

# Start Next.js in development mode after running tests
CMD \
  if [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
  else npm run dev; \
  fi
