services:
  cms:
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    # ports:
    #  - "9229:9229" # Node.js debugging port
    # command: "node --inspect=0.0.0.0:9229 --enable-source-maps --no-deprecation node_modules/.bin/strapi develop -- --watch-admin"
    volumes:
      - ${DEV_CMS_SRC_PATH}:/usr/app/src
  frontend:
    build:
      context: ../frontend
      dockerfile: ../dev-config/Dockerfile.frontend.dev
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ${DEV_FRONTEND_SRC_PATH}:/app/src
