FROM node:18

WORKDIR /usr/app

# For temp files e.g. video thumbnails
RUN mkdir -p /usr/app/tmp

COPY package*.json ./

RUN echo "ls -la"
RUN ls -la /usr/app
RUN echo "COPY . ."
COPY . .

# Add a step to remove node_modules if it was accidentally copied
RUN echo "rm -rf node_*****modules"
RUN rm -rf node_modules

RUN echo "ls -la"
RUN ls -la /usr/app
RUN npm ci

RUN echo "ls -la"
RUN ls -la /usr/app

RUN bash -c "chmod 777 run.sh;"
CMD bash -c "./run.sh"
